server:
  port: 8080

spring:
  application:
    name: pizzaria-service
  datasource:
    url: jdbc:h2:file:/app/dados/pizzariadb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      continue-on-error: true
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
    com:
      bcopstein: DEBUG
imposto:
  leiCorrente: LEI-100